name: build and publish

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*' # We will publish new version for tag which follows 'v*.*.*' format

env:
  SERVICE_NAME: MySDK2
jobs:
  publish-aar:
    runs-on: ubuntu-latest
    #    needs: [ determine_should_publish_new_version, verification ]
    #    if: ${{ needs.determine_should_publish_new_version.outputs.PUBLISH_NEW_VERSION == 'true' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build aar
        run: ./gradlew react-native-library:assemble
      - name: Publish aar
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{github.actor}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GITHUB_TOKEN: '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'
